repos:
  - repo: local
    files: ^sign_language_segmentation/
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: pytest sign_language_segmentation
        language: system
        types: [python]

